server:
  port: 0

spring:
  application:
    name: order-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:h2:mem:testdb
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: yang9386

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

